#!/bin/sh

SD=$(dirname `which $0`)/../scripts
FOSTER_ROOT=$(python $SD/normpath.py $SD/..)
TMPDIR=fosterc-tmp

mkdir ${TMPDIR}

MAYBE_OUT="-o $1.exe"

for arg in $@; do
  if test $arg = "-o"; then
    MAYBE_OUT=""
  fi
done

echo python ${SD}/fosterc.py --bindir ${FOSTER_ROOT}/_obj -I ${FOSTER_ROOT}/stdlib --tmpdir ${TMPDIR} $@ $MAYBE_OUT
python ${SD}/fosterc.py --bindir ${FOSTER_ROOT}/_obj -I ${FOSTER_ROOT}/stdlib --tmpdir ${TMPDIR} $@ $MAYBE_OUT

rm meGCstats.txt
rm -rf ${TMPDIR} $1.postopt.ll $1.preopt.ll
