#!/bin/sh

SD=$(dirname `which $0`)/../scripts
R=$(python $SD/normpath.py $SD/..)

cxxpath () {
  cat $R/_obj/CMakeCache.txt | grep CLANG:FILEPATH | sed 's/CLANG:FILEPATH=//'
}

# Use regular clang instead of clang++
CLANG=$(python $SD/normpath.py `cxxpath`/../clang)

${CLANG} -Werror=division-by-zero $@ -o _runclang.exe
./_runclang.exe
retval=$?
rm -rf _runclang.exe
exit ${retval}

