[package]
name = "fraz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.6"
libc = "*"

[build-dependencies]
cc = "1.0"


